Connect Wallet and Unlock Push profile new flow ready
push-protocol/push-dapp pull request #1518
Opened 2024-05-10 06:04 UTC by abhishek-01k

Things to Review:

- [ ] Code Structure is first priority.
- [ ] Figma Design is Available 
- [ ] New Flow for connecting wallet and creating Push user in Push Chat Flow.
- [ ] Remember Me functionality is working or not. Also , log out is working properly or not.
- [ ] Any other issues related to this PR.

2024-05-10 06:09 UTC, rohitmalhotra1420 commented on src/modules/chat/ChatModule.tsx
> +  useEffect(() => { }, [account, connectedUser?.privateKey]);
I think we can remove it. Right?

2024-05-10 11:54 UTC, mishramonalisha76 requested changes
<img width="228" alt="image" src="https://github.com/push-protocol/push-dapp/assets/42746736/a789e60f-b88b-4810-8d04-8c76afb7f6db">

the disabled unlock profile text color is not right, also the numeric bubbles  size doesnot match with design.

The background of chat is not blurred when connect wallet modal appears.

The background of the connect and unlock overlay is opaque as per design.

The tooltip content that appears on hovering on remember me doesnot have correct line height.Text seems too spread out.


The gap between the 1-2 slider and the buttons are not same as design in mobile view

For the modal version : 
The modal border-radius and border are not as per figma.
Also check the font sizes and font weights too. Some are not matching with figma.

2024-05-13 08:38 UTC, abhishek-01k commented on src/modules/chat/ChatModule.tsx
> +  useEffect(() => { }, [account, connectedUser?.privateKey]);
Removed.

2024-05-13 13:48 UTC, HarshRajat submitted a review, later dismissed

2024-05-13 13:50 UTC, merged