Subscribe change to subscribev2
push-protocol/push-dapp pull request #1524
Opened 2024-05-14 10:50 UTC by abhishek-01k

Changed the subscribe API to subscribeV2 for Opt In and now the user settings are getting updated as per the API call.

2024-05-14 11:01 UTC, rohitmalhotra1420 requested changes
@corlard3y could you also give it a functional review once @abhishek-01k is done with the changes.

@abhishek-01k a loom video with a proper explanation about the changes is much appreciated on this PR.

2024-05-22 07:20 UTC, mishramonalisha76 approved these changes
Functionality looks good to me

2024-05-24 10:33 UTC, abhishek-01k commented on src/helpers/channel/notifSetting.ts
> +        : _notifSettings.push({ value: setting.user, enabled: (setting as ChannelSetting & { type: 2 }).enabled })
We couldn't resolve for this one because both had diff objects.

2024-05-24 10:33 UTC, abhishek-01k commented on src/helpers/channel/notifSetting.ts
> +    );
We couldn't resolve for this one because both had diff objects.

2024-05-27 08:19 UTC, rohitmalhotra1420 approved these changes
Non functional minor fixes, but I am approving it.

Next steps: 
- Get this tested from Kartikey
- Ask him to post his QA finding on the ticket.
- If Qa is successful merge the PR and ask @rohitmalhotra1420 to close this ticket.

2024-05-27 08:19 UTC, rohitmalhotra1420 commented on src/helpers/channel/notifSetting.ts
> +  //TODO: Use array.reduce( preffered) or array.forEach (less preffered) instead of for loop
Comment can be removed

2024-05-27 08:19 UTC, rohitmalhotra1420 commented on src/helpers/channel/notifSetting.ts
> +  // let userSetting = '';
Remove comment

2024-05-27 08:39 UTC, mishramonalisha76 approved these changes

2024-05-27 16:30 UTC, rohitmalhotra1420 approved these changes

2024-05-28 12:43 UTC, GeekyKartikey commented
I have done the QA for this, the opt-in feature is working and also the notification settings are working without any issues. It seems well to me

2024-05-28 13:14 UTC, merged