🐛 [BUG] - [BUMP SDK IN DAPP] Chat badge getting updated for active/opened conversation
push-protocol/push-dapp pull request #1582
Opened 2024-05-27 14:46 UTC by corlard3y

## Pull Request Template

#1580 

- [#1580](https://github.com/push-protocol/push-dapp/issues/1580)

### Description

- **Problem/Feature**:  Chat badge getting updated for Push Bot, and active conversations

### Type of Change

- [x] Bug fix

### Checklist

- [ ] **Quick PR**: Is this a quick PR? Can be approved before finishing a coffee.
  - [ ] Quick PR label added
- [ ] **Not Merge Ready**: Is this PR dependent on some other PR/tasks and not ready to be merged right now.
  - [ ] DO NOT Merge PR label added

### Frontend Guidelines

- [x] Followed frontend guidelines as per the [Guidelines Notion Doc](https://www.notion.so/pushprotocol/Frontend-dApp-Guidelines-1d7806ae3d9e4569a340b563dcd0536c)

### Build & Testing

- [x] No errors in the build terminal
- [x] Engineer has tested the changes on their local environment
- [ ] Engineer has tested the changes on deploy preview

### Screenshots/Video with Explanation

- **Before:** When user clicks on Push Bot from recommended chat section, and sends a message - it updates the badge count which should not be so 
https://www.loom.com/share/0907f4b8040b479aa592bc0fb3d0b1fd?sid=e997494a-8408-43a4-a001-a772ae1ded70

- **After:** Now, when you click on Push Bot from recommended chat, or from the chat preview list. It does not update the badge when you text or get a response. Also, tested regular conversations in the video communicating btw 2 different wallets on my mobile and desktop. So i confirmed this works fine. TEST locallly, cause you need to use PROD so you can get a response from the PUSH BOT to ascertain it is working fine.
https://www.loom.com/share/7ad9b8c7804749b28701feca77d9a2da?sid=40d6aba4-8f52-4aa3-b627-6435fa947aa0
### Additional Context

TEST locallly, cause you need to use PROD so you can get a response from the PUSH BOT to ascertain it is working fine.

### Review & Approvals

- [x] Self-review completed
- [ ] Code review by at least one other engineer
- [ ] Documentation updates if applicable

### Notes

2024-05-29 10:34 UTC, mishramonalisha76 submitted a review, later dismissed

2024-05-29 13:57 UTC, rohitmalhotra1420 submitted a review, later dismissed

2024-05-29 19:20 UTC, corlard3y commented
Bumped sdk to alpha version

cc: @rohitmalhotra1420 @mishramonalisha76

2024-05-30 05:20 UTC, rohitmalhotra1420 requested changes

2024-05-30 05:20 UTC, rohitmalhotra1420 commented on src/components/chat/recommended/Recommended.tsx
> +        console.log(item.payload, 'jojojojoj');
Let's remove the jojojo 😄

2024-06-03 04:56 UTC, rohitmalhotra1420 approved these changes

2024-06-03 10:20 UTC, mishramonalisha76 approved these changes

2024-06-04 10:39 UTC, rohitmalhotra1420 commented
The changes are already there in Dapp as a part of uiweb: 1.6.0-alpha.4

2024-06-04 10:39 UTC, closed without merging