Added Dashboard route and dashboard in the sidebar
push-protocol/push-dapp pull request #1606
Opened 2024-06-05 11:25 UTC by abhishek-01k

## Pull Request Template

#1600 

### Description

Added the Dashboard route and added dashboard button in the sidebar.

- **Problem/Feature**:

### Type of Change

- [ ] New feature

### Frontend Guidelines

- [ ] Followed frontend guidelines as per the [Guidelines Notion Doc](https://www.notion.so/pushprotocol/Frontend-dApp-Guidelines-1d7806ae3d9e4569a340b563dcd0536c)

### Build & Testing

- [ ] No errors in the build terminal
- [ ] Engineer has tested the changes on their local environment
- [ ] Engineer has tested the changes on deploy preview

### Review & Approvals

- [ ] Self-review completed
- [ ] Code review by at least one other engineer
- [ ] Documentation updates if applicable

### Notes

Things that are done:

- [ ] Proper folder structuring is done. However some sub-folders or files are not present feel free to add them according to the usage.

Things that are left in this PR:

- [ ] New sidebar design according to the figma is not done yet.
- [ ] If you will be creating a new component for the Dashboard so feel free to add that component in src/modules/Dashboard/components folder.
- [ ] Logo of the Dashboard is not imported from Blocks because all the sidebar logos are imported from a single file and code is written in that way to access that file. So, Will work on this too.

2024-06-06 08:41 UTC, mishramonalisha76 requested changes
Need to change the folder name of Dashboard to lower case.
Rest everything look good

2024-06-06 08:44 UTC, rohitmalhotra1420 requested changes

2024-06-06 08:44 UTC, rohitmalhotra1420 commented on src/components/MobileNavButton.jsx
> -    case GLOBALS.CONSTANTS.NAVBAR_SECTIONS.SECONDARY:
Why have we done these changes? Is this a previously missing edge case?

2024-06-06 08:44 UTC, rohitmalhotra1420 commented on src/structure/MobileNavigation.tsx
> +      newNavSetup.developersList[1].data.hidden = true;
What does this change do?

2024-06-06 08:44 UTC, rohitmalhotra1420 commented on src/structure/Navigation.tsx
> +      newNavSetup.developersList[0].data.hidden = true;
Why?

2024-06-07 11:30 UTC, abhishek-01k commented on src/config/NavigationList.js
> -          fg: themeDark.headerTagFg,
Its not deleted its present

2024-06-07 12:29 UTC, rohitmalhotra1420 requested changes

2024-06-07 12:29 UTC, rohitmalhotra1420 commented on src/modules/Dashboard/Dashboard.tsx
> +import { FC } from 'react';
@abhishek-01k folder name still not fixed. It needs to be modules/dashboard/Dashboard.tsx

2024-06-10 07:30 UTC, rohitmalhotra1420 approved these changes

2024-06-10 07:30 UTC, merged