Feat/Base Chain support
push-protocol/push-dapp pull request #1608
Opened 2024-06-05 15:23 UTC by corlard3y

## Pull Request Template

### Ticket Number

- [Ticket Number](link-to-ticket)

### Description

- **Problem/Feature**:

### Type of Change

- [ ] Bug fix
- [ ] New feature
- [ ] Code refactor
- [ ] Documentation update
- [ ] Other (please describe):

### Checklist

- [ ] **Quick PR**: Is this a quick PR? Can be approved before finishing a coffee.
  - [ ] Quick PR label added
- [ ] **Not Merge Ready**: Is this PR dependent on some other PR/tasks and not ready to be merged right now.
  - [ ] DO NOT Merge PR label added

### Frontend Guidelines

- [ ] Followed frontend guidelines as per the [Guidelines Notion Doc](https://www.notion.so/pushprotocol/Frontend-dApp-Guidelines-1d7806ae3d9e4569a340b563dcd0536c)

### Build & Testing

- [ ] No errors in the build terminal
- [ ] Engineer has tested the changes on their local environment
- [ ] Engineer has tested the changes on deploy preview

### Screenshots/Video with Explanation

- **Before:** Explain the previous behavior

- **After:** What's changed now

### Additional Context

### Review & Approvals

- [ ] Self-review completed
- [ ] Code review by at least one other engineer
- [ ] Documentation updates if applicable

### Notes

2024-06-14 07:30 UTC, mishramonalisha76 requested changes
LGTM

2024-06-14 07:31 UTC, mishramonalisha76 submitted a review, later dismissed

2024-07-16 09:35 UTC, rohitmalhotra1420 commented on src/services/alias/getAliasDetails.ts
> +  console.log(account, aliasChainIdToChainName[chainId], appConfig.appEnv);
let's remove this.

2024-07-16 09:35 UTC, rohitmalhotra1420 approved these changes

2024-07-16 11:35 UTC, closed without merging