DApp-1549 Dropdown/Menu component
push-protocol/push-dapp pull request #1648
Opened 2024-06-17 10:44 UTC by corlard3y

## Pull Request Template

#1545 

- [#1545](link-to-ticket)

### Description

- Introduce menu in blocks folder which has Menu component, which serves as parent component to the Menu Item component
- Added MenuItem component, which is the list of all items in the Menu component. 
- Added Dropdown component too, which has a trigger to open the Menu(overlay), either on Hover action, or onClick action.
- Also, added light and dark mode support to these components 

### Problem/Feature
Create a dropdown and menu package in the blocks folder and introduce these dropdown and menu items as a react component so that these could be reused in other component.

Figma: https://www.figma.com/design/FvJL0JWHlsVohsHTERB1Lh/Push-Design-Foundations-%5BFuture%5D?node-id=2663-23523&t=XRHuzgCLtQkYnb4h-1

### Type of Change

- [ ] Bug fix
- [x] New feature
- [ ] Code refactor
- [ ] Documentation update
- [ ] Other (please describe):

### Checklist

- [ ] **Quick PR**: Is this a quick PR? Can be approved before finishing a coffee.
  - [ ] Quick PR label added
- [ ] **Not Merge Ready**: Is this PR dependent on some other PR/tasks and not ready to be merged right now.
  - [ ] DO NOT Merge PR label added

### Frontend Guidelines

- [ ] Followed frontend guidelines as per the [Guidelines Notion Doc](https://www.notion.so/pushprotocol/Frontend-dApp-Guidelines-1d7806ae3d9e4569a340b563dcd0536c)

### Build & Testing

- [x] No errors in the build terminal
- [ ] Engineer has tested the changes on their local environment
- [ ] Engineer has tested the changes on deploy preview

### Screenshots/Video with Explanation

- **Before:** Explain the previous behavior

- **After:** What's changed now

### Additional Context

### Review & Approvals

- [ ] Self-review completed
- [ ] Code review by at least one other engineer
- [ ] Documentation updates if applicable

### Notes

2024-06-17 10:44 UTC, corlard3y commented
Added the basic flow of the dropdown and Menu, Pls lmk what changes can be added. Also, used hardcoding within the dropdown component so I will need your assistance/direction within the children(isOpen) param, and title ig @rohitmalhotra1420

2024-06-20 06:20 UTC, rohitmalhotra1420 requested changes
Needs signficant amount of changes. Let's connect for this.

2024-06-20 06:20 UTC, rohitmalhotra1420 commented on src/blocks/dropdown/Dropdown.tsx
> +import styled, { FlattenSimpleInterpolation } from 'styled-components';
```suggestion
import { forwardRef, useState } from 'react';
import styled from 'styled-components';
```
remove unused imports

2024-06-20 06:20 UTC, rohitmalhotra1420 commented on src/blocks/dropdown/Dropdown.tsx
> +      ref={ref}
```suggestion
      ref={ref}
```

Fix the typescript error

2024-06-20 06:20 UTC, rohitmalhotra1420 commented on src/blocks/dropdown/Dropdown.tsx
> +  shouldForwardProp: (prop, defaultValidatorFn) => !['mode'].includes(prop) && defaultValidatorFn(prop),
Add all the props in this array which are passed down to the html tags

2024-06-20 06:20 UTC, rohitmalhotra1420 commented on src/blocks/dropdown/Dropdown.tsx
> +    padding: 10px 15px;
```suggestion
    padding: 10px 15px;
```
use `var(--s0)` format for gap, padding and margins

2024-06-20 06:20 UTC, rohitmalhotra1420 commented on src/blocks/dropdown/Dropdown.tsx
> +    border-radius: 20px;
```suggestion
    border-radius: 20px;
```
use var(--r0) format for border-radius

2024-06-20 06:20 UTC, rohitmalhotra1420 commented on src/blocks/dropdown/Dropdown.tsx
> +      color: #657795;
use var(--pink-100) format for colors

2024-06-20 06:20 UTC, rohitmalhotra1420 commented on src/blocks/dropdown/Dropdown.tsx
> +    margin-top: 3px;
Same

2024-06-20 06:20 UTC, rohitmalhotra1420 commented on src/blocks/dropdown/Dropdown.tsx
> +    padding: 10px 15px;
@corlard3y only the css variables mentioned App.tsx are to be allowed.

2024-06-20 06:20 UTC, rohitmalhotra1420 commented on src/blocks/dropdown/Dropdown.tsx
> +      </div>
Why do we need this actions button? the overlay should be visible when the trigger element is clicked. Right now the overlay is visible when the Actions text is clicked.

<img width="434" alt="Screenshot 2024-06-20 at 11 35 18 AM" src="https://github.com/push-protocol/push-dapp/assets/25508878/f876d981-3fa2-483e-a6b0-5fb3e9285649">

2024-06-20 06:20 UTC, rohitmalhotra1420 commented on src/blocks/dropdown/Dropdown.types.ts
> +  trigger: 'click' | 'hover';
Trigger should be optional and click by default.

2024-06-20 06:20 UTC, rohitmalhotra1420 commented on src/blocks/dropdown/Dropdown.types.ts
> +  children?: (isOpen: boolean) => ReactNode;
```suggestion
  children: (isOpen: boolean) => ReactNode;
```
children should be mandatory for dropdown

2024-06-20 06:20 UTC, rohitmalhotra1420 commented on src/blocks/dropdown/Dropdown.tsx
> +    <StyledDropdown
<img width="208" alt="Screenshot 2024-06-20 at 11 38 33 AM" src="https://github.com/push-protocol/push-dapp/assets/25508878/c71e9ea0-1805-4f8d-a129-eae6295b2ede">

@corlard3y 
The dropdown doesn't follows the correct figma design:https://www.figma.com/design/FvJL0JWHlsVohsHTERB1Lh/Push-Design-Foundations-[Future]?node-id=2663-23523&t=Hr7vGDBgMGSAlcxO-0

- Spacing between icon and label is off.
- There is no minimum width of the overlay item  as shown in figma. The overlay width is decided by the width of the label width.
-

2024-06-20 06:20 UTC, rohitmalhotra1420 commented on src/blocks/dropdown/Dropdown.tsx
> +    <StyledDropdown
<img width="232" alt="Screenshot 2024-06-20 at 11 41 20 AM" src="https://github.com/push-protocol/push-dapp/assets/25508878/0eb323ce-fcbf-4fe1-b51d-c549553a3d1d">
<img width="163" alt="Screenshot 2024-06-20 at 11 41 47 AM" src="https://github.com/push-protocol/push-dapp/assets/25508878/a174bc64-a201-4784-a911-be1256074304">


Hover css is off

2024-06-20 06:20 UTC, rohitmalhotra1420 commented on src/blocks/dropdown/Dropdown.tsx
> +    <StyledDropdown
overlay is getting cut off in scroll container.

<img width="208" alt="Screenshot 2024-06-20 at 11 38 33 AM" src="https://github.com/push-protocol/push-dapp/assets/25508878/c71e9ea0-1805-4f8d-a129-eae6295b2ede">

2024-06-20 06:20 UTC, rohitmalhotra1420 commented on src/blocks/dropdown/Dropdown.tsx
> +    <StyledDropdown
<img width="754" alt="Screenshot 2024-06-20 at 11 43 04 AM" src="https://github.com/push-protocol/push-dapp/assets/25508878/a2493c8c-58cf-4c7b-a6c5-7017eecf288f">

Overlay is not overlapping the scroll container and getting scrolled with the trigger element inside the scroll container.

**Ideally overlay should be a portal and should be hidden when the trigger element is out of viewport.**

2024-06-20 06:20 UTC, rohitmalhotra1420 commented on src/blocks/menu/MenuItem.tsx
> +      {icon && <span className='menu-icon'>{icon()}</span>}
```suggestion
      {icon && <span className='menu-icon'>{icon}</span>}
```

This is breaking at the moment.

2024-06-20 06:20 UTC, rohitmalhotra1420 commented on src/blocks/menu/MenuItem.tsx
> +      {icon && <span className='menu-icon'>{icon()}</span>}
- icon colors for light and dark mode are also off.
- icon size are are incorrect.
<img width="152" alt="Screenshot 2024-06-20 at 11 44 37 AM" src="https://github.com/push-protocol/push-dapp/assets/25508878/143d81ad-e5d8-4f07-b6ce-63ae8fd484aa">
<img width="120" alt="Screenshot 2024-06-20 at 11 45 59 AM" src="https://github.com/push-protocol/push-dapp/assets/25508878/1bbdbe48-0be6-4fea-98c4-0e327b90ac9d">

2024-06-20 06:20 UTC, rohitmalhotra1420 commented on src/blocks/menu/MenuItem.tsx
> +  /* Extra CSS props */
Use var(--s0) format for gap, margin and padding.
Use var(--r0) format for border-radius.
Use var(--pink-100) format for color and background-color.

2024-06-20 06:20 UTC, rohitmalhotra1420 commented on src/blocks/dropdown/Dropdown.types.ts
> +  css?: FlattenSimpleInterpolation;
FlattenSimpleInterpolation is not imported from styled-components.

2024-06-20 06:20 UTC, rohitmalhotra1420 commented on src/blocks/menu/Menu.tsx
> +import { FC,forwardRef } from 'react';
<img width="695" alt="Screenshot 2024-06-20 at 11 48 34 AM" src="https://github.com/push-protocol/push-dapp/assets/25508878/4407fae5-f0b0-45a9-87aa-cbd1ac939738">
Needs fixes

2024-06-20 06:20 UTC, rohitmalhotra1420 commented on src/blocks/menu/Menu.types.ts
> +import { CSSProperties, ReactNode } from 'react';
Needs fixes
<img width="999" alt="Screenshot 2024-06-20 at 11 49 25 AM" src="https://github.com/push-protocol/push-dapp/assets/25508878/0a98aad8-f996-4bb5-9230-5048b985e8a3">

2024-06-20 06:20 UTC, rohitmalhotra1420 commented on src/blocks/menu/MenuItem.tsx
> +import { FC,forwardRef } from 'react';
Needs fixes
<img width="943" alt="Screenshot 2024-06-20 at 11 49 50 AM" src="https://github.com/push-protocol/push-dapp/assets/25508878/6442a18c-f478-4105-abb8-def652cb340b">

2024-07-02 09:39 UTC, closed without merging