UserPushSDKInstance returns null randomly on dapp
push-protocol/push-dapp pull request #1763
Opened 2024-07-22 14:48 UTC by corlard3y

## Pull Request Template

#1718 

### Description

- **Problem/Feature**:
UserPushSDKInstance return null randomly on dapp, it is getting reset from the redux state. It is because the UseEffect that resets userSlice from redux state runs everytime, even when account(dependency array) does not change. I added a mounted useRef logic to make it update only when account changes

### Type of Change

- [x] Bug fix
- [ ] New feature
- [ ] Code refactor
- [ ] Documentation update
- [ ] Other (please describe):

### Checklist

- [ ] **Quick PR**: Is this a quick PR? Can be approved before finishing a coffee.
  - [ ] Quick PR label added
- [ ] **Not Merge Ready**: Is this PR dependent on some other PR/tasks and not ready to be merged right now.
  - [ ] DO NOT Merge PR label added

### Frontend Guidelines

- [x] Followed frontend guidelines as per the [Guidelines Notion Doc](https://www.notion.so/pushprotocol/Frontend-dApp-Guidelines-1d7806ae3d9e4569a340b563dcd0536c)

### Build & Testing

- [x] No errors in the build terminal
- [ ] Engineer has tested the changes on their local environment
- [ ] Engineer has tested the changes on deploy preview

### Screenshots/Video with Explanation

- **Before:** Explain the previous behavior

- **After:** What's changed now

### Additional Context

### Review & Approvals

- [ ] Self-review completed
- [ ] Code review by at least one other engineer
- [ ] Documentation updates if applicable

### Notes

2024-07-23 06:08 UTC, rohitmalhotra1420 requested changes

2024-07-23 06:08 UTC, rohitmalhotra1420 commented on src/App.tsx
> +  const mounted = useRef<any>();
Why not use useState here instead of useRef?

2024-07-23 08:53 UTC, rohitmalhotra1420 approved these changes

2024-07-23 08:53 UTC, rohitmalhotra1420 approved these changes
@abhishek-01k could you test this out functionally.

2024-07-24 09:03 UTC, abhishek-01k approved these changes

2024-07-24 09:47 UTC, merged