DApp-1690 dashboard analytics with stakingpools
push-protocol/push-dapp pull request #1780
Opened 2024-07-29 16:05 UTC by rohitmalhotra1420

## Pull Request Template

### Ticket Number

- [1690](https://github.com/push-protocol/push-dapp/issues/1690)

### Description

- Implemented the notification, message and subscriber count on /welcome page. These counts matches the push.network numbers.
- Implemented the staking pools section on /welcome page.

- **Problem/Feature**:

### Type of Change

- [ ] Bug fix
- [ ] New feature
- [ ] Code refactor
- [ ] Documentation update
- [ ] Other (please describe):

### Checklist

- [ ] **Quick PR**: Is this a quick PR? Can be approved before finishing a coffee.
  - [ ] Quick PR label added
- [ ] **Not Merge Ready**: Is this PR dependent on some other PR/tasks and not ready to be merged right now.
  - [ ] DO NOT Merge PR label added

### Frontend Guidelines

- [ ] Followed frontend guidelines as per the [Guidelines Notion Doc](https://www.notion.so/pushprotocol/Frontend-dApp-Guidelines-1d7806ae3d9e4569a340b563dcd0536c)

### Build & Testing

- [ ] No errors in the build terminal
- [ ] Engineer has tested the changes on their local environment
- [ ] Engineer has tested the changes on deploy preview

### Screenshots/Video with Explanation

- **Before:** Explain the previous behavior

- **After:** What's changed now

### Additional Context

### Review & Approvals

- [ ] Self-review completed
- [ ] Code review by at least one other engineer
- [ ] Documentation updates if applicable

### Notes

2024-07-29 20:14 UTC, corlard3y reviewed
![Screenshot 2024-07-29 at 21 01 33](https://github.com/user-attachments/assets/96ac8ba2-1ad9-47b8-b4f7-8d01e4e4d421)

Just noticed the Total Value Locked formatting not working like the rest of the figures.

2024-07-30 07:05 UTC, rohitmalhotra1420 commented
> ![Screenshot 2024-07-29 at 21 01 33](https://private-user-images.githubusercontent.com/38462689/353222461-96ac8ba2-1ad9-47b8-b4f7-8d01e4e4d421.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMjMzODgsIm5iZiI6MTcyMjMyMzA4OCwicGF0aCI6Ii8zODQ2MjY4OS8zNTMyMjI0NjEtOTZhYzhiYTItMWFkOS00N2I4LWI0ZjctOGQwMWU0ZTRkNDIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDA3MDQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzZmIxNWE3ODM1NzUyNjY5MjQ0MzhmMWJjY2FkNDg4MmE3ZDgxZjYxMjc2ZWIxMDQ1YjhiYmQzNDg3M2RmMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1lZXO16w3OQDes9eFznE2678OlMEPs9pzlLVp3aFI0I)
> 
> Just noticed the Total Value Locked formatting not working like the rest of the figures.

Fixed it @corlard3y

2024-07-30 08:17 UTC, mishramonalisha76 requested changes
<img width="355" alt="image" src="https://github.com/user-attachments/assets/d0fc1038-e4c6-4cac-8f7b-167d58dfbebb">
The description doesnot look like the one in figma, needs to be a lesser width.
Also a little bit more gap between the skeleton and the apr, staked, would look better.
The values keeps on loading and i get the exception division by zero. I think its coming intermittently.

2024-07-30 08:19 UTC, mishramonalisha76 commented on src/queries/models/analytics/getSubscriberCountModelCreator.ts
> +  let subscriberArray: any[] = [];
can we add proper type to the array inspite of any

2024-07-30 09:33 UTC, mishramonalisha76 approved these changes

2024-07-30 09:35 UTC, merged