Update BASE and LINEA support
push-protocol/push-dapp pull request #1818
Opened 2024-08-20 14:57 UTC by corlard3y

## Pull Request Template

#1636 

### Description

- **Problem/Feature**:
- So we are basically just adding Linea chain support, it’s just going to be a new chain like the others we have, from polygon, Arbitrum, cyber and the rest that have been added beforehand. So this is a new one called Linea Chain - So you can create channels, send notifications on this chain.
- 
- Uncomment Base Chain changes

### Type of Change

- [ ] Bug fix
- [x] New feature
- [ ] Code refactor
- [ ] Documentation update
- [ ] Other (please describe):

### Checklist

- [ ] **Quick PR**: Is this a quick PR? Can be approved before finishing a coffee.
  - [ ] Quick PR label added
- [ ] **Not Merge Ready**: Is this PR dependent on some other PR/tasks and not ready to be merged right now.
  - [ ] DO NOT Merge PR label added

### Frontend Guidelines

- [x] Followed frontend guidelines as per the [Guidelines Notion Doc](https://www.notion.so/pushprotocol/Frontend-dApp-Guidelines-1d7806ae3d9e4569a340b563dcd0536c)

### Build & Testing

- [ ] No errors in the build terminal
- [ ] Engineer has tested the changes on their local environment
- [ ] Engineer has tested the changes on deploy preview

### Screenshots/Video with Explanation

- **Before:** Explain the previous behavior

- **After:** What's changed now

### Additional Context

### Review & Approvals

- [ ] Self-review completed
- [ ] Code review by at least one other engineer
- [ ] Documentation updates if applicable

### Notes

2024-08-22 11:16 UTC, mishramonalisha76 requested changes
config.alpha needs to be updated too

2024-08-22 11:20 UTC, mishramonalisha76 requested changes
<img width="392" alt="image" src="https://github.com/user-attachments/assets/68c4fdd0-5f21-4417-bf6e-211c527d51a7">
 the base and linea icon in add new chain page arent of the correct size, it increases the select size

2024-08-22 11:38 UTC, corlard3y commented
Fixed all comments @mishramonalisha76

2024-08-22 12:02 UTC, mishramonalisha76 approved these changes

2024-08-26 09:56 UTC, abhishek-01k approved these changes

2024-08-26 10:32 UTC, rohitmalhotra1420 requested changes

2024-08-26 10:36 UTC, corlard3y commented on public/svg/Linea.svg
Yes, we do. The main Chain switcher component in the header uses that till we update it to use the new Icons block component from the root files across all chains. Check LOGO_FROM_CHAIN_ID in UtilityHelper @rohitmalhotra1420

2024-08-26 11:00 UTC, rohitmalhotra1420 approved these changes

2024-08-26 11:00 UTC, merged