DApp-1799 blocks/table
push-protocol/push-dapp pull request #1824
Opened 2024-08-22 11:04 UTC by rohitmalhotra1420

## Pull Request Template

### Ticket Number

- [1799](https://github.com/push-protocol/push-dapp/issues/1799)

### Description

- Implemented Table component in blocks.

- **Problem/Feature**:

### Type of Change

- [ ] Bug fix
- [ ] New feature
- [ ] Code refactor
- [ ] Documentation update
- [ ] Other (please describe):

### Checklist

- [ ] **Quick PR**: Is this a quick PR? Can be approved before finishing a coffee.
  - [ ] Quick PR label added
- [ ] **Not Merge Ready**: Is this PR dependent on some other PR/tasks and not ready to be merged right now.
  - [ ] DO NOT Merge PR label added

### Frontend Guidelines

- [ ] Followed frontend guidelines as per the [Guidelines Notion Doc](https://www.notion.so/pushprotocol/Frontend-dApp-Guidelines-1d7806ae3d9e4569a340b563dcd0536c)

### Build & Testing

- [ ] No errors in the build terminal
- [ ] Engineer has tested the changes on their local environment
- [ ] Engineer has tested the changes on deploy preview

### Screenshots/Video with Explanation

- **Before:** Explain the previous behavior

- **After:** What's changed now
<img width="1201" alt="Screenshot 2024-08-22 at 4 20 35 PM" src="https://github.com/user-attachments/assets/5ee093e2-af5f-4d11-a8b8-a7a2c8100f1b">
<img width="1183" alt="Screenshot 2024-08-22 at 4 33 53 PM" src="https://github.com/user-attachments/assets/c6ae5302-2dc0-404c-81fc-11a2c68aa15c">

### Additional Context

### Review & Approvals

- [ ] Self-review completed
- [ ] Code review by at least one other engineer
- [ ] Documentation updates if applicable

### Notes

2024-08-22 11:28 UTC, rohitmalhotra1420 commented
How to use Table?

   ```
<Box
        height="300px"
        width="1200px"
      >
        <Table
          fixedHeader
          columns={[
            {
              title: 'STATUS',
              dataIndex: 'status',
              width: '100px',
              fixed: 'left',
              render: (text) => (
                <Tag
                  label="Success"
                  variant={text as TagVariant}
                />
              ),
            },
            {
              title: 'TX HASH',
              dataIndex: 'txHash',
              width: '150px',
            },
            {
              title: 'BLOCK HASH',
              dataIndex: 'blockHash',
              width: '150px',
            },
            {
              title: 'FROM',
              dataIndex: 'from',
              width: '150px',
              render: (text) => (
                <Box
                  display="flex"
                  gap="spacing-xxs"
                  alignItems="center"
                >
                  <Ethereum
                    width={16}
                    height={16}
                  />
                  <Link to="#">{text}</Link>
                </Box>
              ),
            },
            {
              title: 'TO',
              dataIndex: 'to',
              width: '150px',
              render: (text) => (
                <Box
                  display="flex"
                  gap="spacing-xxs"
                  alignItems="center"
                >
                  <Ethereum
                    width={16}
                    height={16}
                  />
                  <Link to="#">{text}</Link>
                </Box>
              ),
            },
            { title: 'CATEGORY', dataIndex: 'category', width: '120px' },
            { title: 'AGE', dataIndex: 'age', width: '80px' },
            {
              title: 'ACTIONS',
              dataIndex: 'actions',
              width: '250px',
              fixed: 'right',
              render: (text, record) => (
                <Box
                  display="flex"
                  gap="spacing-xxs"
                >
                  <Button
                    size="extraSmall"
                    variant="outline"
                    onClick={() => {
                      console.log(record);
                    }}
                  >
                    Accept
                  </Button>
                  <Button
                    size="extraSmall"
                    variant="dangerSecondary"
                    onClick={() => {
                      console.log(record);
                    }}
                  >
                    Reject
                  </Button>
                </Box>
              ),
            },
          ]}
          dataSource={[
            {
              id: '0',
              status: 'success',
              txHash: 'd2eonci2j2312321321e1w000320ni23ni3r9d93nd',
              blockHash: 'd2eonci2j2312321321e1w000320ni23ni3r9d93nd',
              from: '323kmi2j2312321321e1w000320ni23ni3r9d93nd',
              to: 'd2eonci2j2312321321e1w000320ni23ni3r9d93nd',
              category: 'Notification',
              age: '2s ago',
            },
            {
              id: '1',
              status: 'success',
              txHash: 'd2eonci2j2312321321e1w000320ni23ni3r9d93nd',
              blockHash: 'd2eonci2j2312321321e1w000320ni23ni3r9d93nd',
              from: '323kmi2j2312321321e1w000320ni23ni3r9d93nd',
              to: 'd2eonci2j2312321321e1w000320ni23ni3r9d93nd',
              category: 'Notification',
              age: '2s ago',
            },
            {
              id: '2',
              status: 'success',
              txHash: 'd2eonci2j2312321321e1w000320ni23ni3r9d93nd',
              blockHash: 'd2eonci2j2312321321e1w000320ni23ni3r9d93nd',
              from: '323kmi2j2312321321e1w000320ni23ni3r9d93nd',
              to: 'd2eonci2j2312321321e1w000320ni23ni3r9d93nd',
              category: 'Notification',
              age: '2s ago',
            },
            {
              id: '3',
              status: 'success',
              txHash: 'd2eonci2j2312321321e1w000320ni23ni3r9d93nd',
              blockHash: 'd2eonci2j2312321321e1w000320ni23ni3r9d93nd',
              from: '323kmi2j2312321321e1w000320ni23ni3r9d93nd',
              to: 'd2eonci2j2312321321e1w000320ni23ni3r9d93nd',
              category: 'Notification',
              age: '2s ago',
            },
            {
              id: '4',
              status: 'success',
              txHash: 'd2eonci2j2312321321e1w000320ni23ni3r9d93nd',
              blockHash: 'd2eonci2j2312321321e1w000320ni23ni3r9d93nd',
              from: '323kmi2j2312321321e1w000320ni23ni3r9d93nd',
              to: 'd2eonci2j2312321321e1w000320ni23ni3r9d93nd',
              category: 'Notification',
              age: '2s ago',
            },
            {
              id: '5',
              status: 'success',
              txHash: 'd2eonci2j2312321321e1w000320ni23ni3r9d93nd',
              blockHash: 'd2eonci2j2312321321e1w000320ni23ni3r9d93nd',
              from: '323kmi2j2312321321e1w000320ni23ni3r9d93nd',
              to: 'd2eonci2j2312321321e1w000320ni23ni3r9d93nd',
              category: 'Notification',
              age: '2s ago',
            },
            {
              id: '6',
              status: 'success',
              txHash: 'd2eonci2j2312321321e1w000320ni23ni3r9d93nd',
              blockHash: 'd2eonci2j2312321321e1w000320ni23ni3r9d93nd',
              from: '323kmi2j2312321321e1w000320ni23ni3r9d93nd',
              to: 'd2eonci2j2312321321e1w000320ni23ni3r9d93nd',
              category: 'Notification',
              age: '2s ago',
            },
            {
              id: '7',
              status: 'success',
              txHash: 'd2eonci2j2312321321e1w000320ni23ni3r9d93nd',
              blockHash: 'd2eonci2j2312321321e1w000320ni23ni3r9d93nd',
              from: '323kmi2j2312321321e1w000320ni23ni3r9d93nd',
              to: 'd2eonci2j2312321321e1w000320ni23ni3r9d93nd',
              category: 'Notification',
              age: '2s ago',
            },
            {
              id: '8',
              status: 'success',
              txHash: 'd2eonci2j2312321321e1w000320ni23ni3r9d93nd',
              blockHash: 'd2eonci2j2312321321e1w000320ni23ni3r9d93nd',
              from: '323kmi2j2312321321e1w000320ni23ni3r9d93nd',
              to: 'd2eonci2j2312321321e1w000320ni23ni3r9d93nd',
              category: 'Notification',
              age: '2s ago',
            },
            {
              id: '9',
              status: 'success',
              txHash: 'd2eonci2j2312321321e1w000320ni23ni3r9d93nd',
              blockHash: 'd2eonci2j2312321321e1w000320ni23ni3r9d93nd',
              from: '323kmi2j2312321321e1w000320ni23ni3r9d93nd',
              to: 'd2eonci2j2312321321e1w000320ni23ni3r9d93nd',
              category: 'Notification',
              age: '2s ago',
            },
            {
              id: '10',
              status: 'success',
              txHash: 'd2eonci2j2312321321e1w000320ni23ni3r9d93nd',
              blockHash: 'd2eonci2j2312321321e1w000320ni23ni3r9d93nd',
              from: '323kmi2j2312321321e1w000320ni23ni3r9d93nd',
              to: 'd2eonci2j2312321321e1w000320ni23ni3r9d93nd',
              category: 'Notification',
              age: '2s ago',
            },
          ]}
        />
      </Box>
```

2024-08-22 15:27 UTC, mishramonalisha76 requested changes

2024-08-22 15:27 UTC, mishramonalisha76 commented on src/blocks/table/index.ts
> +export * from './Table';
We also need to export TableProps

2024-08-23 07:59 UTC, mishramonalisha76 approved these changes

2024-08-23 08:22 UTC, merged