Channel details page
push-protocol/push-dapp pull request #1861
Opened 2024-09-20 08:48 UTC by mishramonalisha76

## Pull Request Template

### Ticket Number

- [1856](#1856 )

### Description

- **Problem/Feature**:

### Type of Change

- [ ] Bug fix
- [ ] New feature
- [ ] Code refactor
- [ ] Documentation update
- [ ] Other (please describe):

### Checklist

- [ ] **Quick PR**: Is this a quick PR? Can be approved before finishing a coffee.
  - [ ] Quick PR label added
- [ ] **Not Merge Ready**: Is this PR dependent on some other PR/tasks and not ready to be merged right now.
  - [ ] DO NOT Merge PR label added

### Frontend Guidelines

- [ ] Followed frontend guidelines as per the [Guidelines Notion Doc](https://www.notion.so/pushprotocol/Frontend-dApp-Guidelines-1d7806ae3d9e4569a340b563dcd0536c)

### Build & Testing

- [ ] No errors in the build terminal
- [ ] Engineer has tested the changes on their local environment
- [ ] Engineer has tested the changes on deploy preview

### Screenshots/Video with Explanation

- **Before:** Explain the previous behavior

- **After:** What's changed now

### Additional Context

### Review & Approvals

- [ ] Self-review completed
- [ ] Code review by at least one other engineer
- [ ] Documentation updates if applicable

### Notes

2024-09-20 11:27 UTC, rohitmalhotra1420 commented
@mishramonalisha76 

- Skeleton state is not working correctly.
- Spacing between notifications is not correct.
- Last notification is not visible 
- Infinite scroll loader not visible for the channel is not visible
- last channel icon is getting truncated.
- When i load the channel detail page, initially broken channel img with some data is visible and after that skeleton is visible.
- The channel icon will also have a border radius and border.
- Channel icon is shrinking in mobile view.

2024-09-25 09:40 UTC, rohitmalhotra1420 requested changes
@mishramonalisha76 to fix the PR comments.

2024-09-25 09:40 UTC, rohitmalhotra1420 commented on src/modules/channelDetails/components/ChannelDetail.tsx
> +              display={{ dp: 'inline', ml: 'none' }}
```suggestion
              display={{ initial: 'inline', ml: 'none' }}
```

Fix this everywhere in this PR.

2024-09-25 09:40 UTC, rohitmalhotra1420 commented on src/modules/channelDetails/components/ChannelDetail.tsx
> +                {`Show ${!showMore ? 'More' : 'Less'}`}
This should only be visible if the char length is above a certain limit.

2024-09-25 09:40 UTC, rohitmalhotra1420 commented on src/modules/channelDetails/components/ChannelDetail.tsx
> +              {!showMore ? (channel?.info || '').substring(0, 250) : channel?.info || ''}
Extract this out in a const

2024-09-25 09:40 UTC, rohitmalhotra1420 commented on src/modules/channelDetails/components/ChannelDetail.tsx
> +  //notification component doesnot update in sdk
Remove it.

2024-09-25 09:40 UTC, rohitmalhotra1420 commented on src/modules/channelDetails/ChannelDetails.tsx
> +  }, [id]);
Add docstring comments for this hook.

2024-09-25 09:40 UTC, rohitmalhotra1420 commented on src/modules/channelDetails/ChannelDetails.tsx
> +    channelsList.length && (
```suggestion
    channelsList?.length && (
```

2024-09-25 11:14 UTC, mishramonalisha76 commented on src/queries/hooks/channels/useGetChannelsList.ts
> +  sort: ChannelListParams['sort'];
order, tag, chain and sort can be optional

2024-09-25 12:47 UTC, mishramonalisha76 commented
The font weight of the channel title in channel listing page doesnot match the one in figma (700 instead of 500 ) @rohitmalhotra1420

2024-09-27 07:34 UTC, abhishek-01k submitted a review, later dismissed

2024-10-18 10:26 UTC, rohitmalhotra1420 approved these changes

2024-10-18 10:26 UTC, rohitmalhotra1420 commented on src/modules/channels/Channels.utils.ts
> +export const filterFrontendChannels = (channels: ChannelDetails[], filter: Filters): Array<string> => {
```suggestion
export const getSuggestedChannels = (channels: ChannelDetails[], filter: Filters): Array<string> => {
```

2024-10-18 10:26 UTC, rohitmalhotra1420 commented on src/modules/channels/Channels.utils.ts
> +export const showFrontendChannels = (filters: Filters) => {
```suggestion
export const showSuggestedChannels = (filters: Filters) => {
```

2024-10-18 10:26 UTC, rohitmalhotra1420 commented on src/modules/channels/Channels.tsx
> +  const filteredFrontendChannels = filterFrontendChannels(channels, filters);
```suggestion
  const suggestedChannels = getSuggestedChannels(channels, filters);
```

2024-10-18 10:26 UTC, rohitmalhotra1420 commented on src/modules/channels/Channels.tsx
> +            frontendChannels={filteredFrontendChannels}
```suggestion
            suggestedChannels={suggestedChannels}
```

2024-10-18 10:26 UTC, rohitmalhotra1420 commented on src/modules/channels/components/AllChannelsList.tsx
> +  frontendChannels: Array<string>;
```suggestion
  suggestedChannels: Array<string>;
```

2024-10-18 10:26 UTC, rohitmalhotra1420 commented on src/modules/channels/components/FrontendChannelListItem.tsx
> +const FrontendChannelListItem: FC<FrontendChannelListItemProps> = ({ channelAddress }) => {
```suggestion
const SuggestedChannelListItem: FC<FrontendChannelListItemProps> = ({ channelAddress }) => {
```

2024-10-18 10:26 UTC, merged